# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11H5BWS7D7xVERRLRKm4Gb8S7x7yHhtIl
"""

import requests
import pandas as pd

def get_breweries_by_state(state="california", per_page=10):
    url = f"https://api.openbrewerydb.org/v1/breweries?by_state={state}&per_page={per_page}"
    response = requests.get(url)
    response.raise_for_status()
    data = response.json()
    return data

def main():
    print("Загружаем данные о пивоварнях из Open Brewery DB")
    breweries = get_breweries_by_state("colorado", 10)

    # Преобразуем в DataFrame
    df = pd.DataFrame(breweries)
    print(df[["name", "brewery_type", "city", "state", "website_url"]])

    # Сохраняем в CSV
    df.to_csv("breweries.csv", index=False)
    print("\nДанные сохранены в breweries.csv")

if __name__ == "__main__":
    main()