# -*- coding: utf-8 -*-
"""write_to_db.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JWb2dq0f7md5qBmZUmQKjJl4sevUiWTm
"""

from sqlalchemy import create_engine, text, inspect
import sqlite3
import os
import pandas as pd

# === Определяем путь к текущему скрипту ===
script_path = os.path.dirname(os.path.abspath(__file__))

# === Подключаемся к creds.db и читаем параметры доступа ===
creds_path = script_path + "\\creds.db"
conn = sqlite3.connect(creds_path)
cur = conn.cursor()

cur.execute("SELECT * FROM access LIMIT 1;")
row = [r for r in cur.fetchall()]
cur.execute("PRAGMA table_info(access)")
cols = [r for r in cur.fetchall()]
conn.close()

# создаём словарь с параметрами
for i in range(len(cols)):
    cols[i] = list(cols[i])
cols_transpose = [list(row) for row in zip(*cols)]
data = dict(zip(cols_transpose[1], row[0]))

db_user = data['user']
db_password = data['pass']
db_url = data['url']
db_port = data['port']
db_root_base = 'homeworks'

# === Загружаем CSV-файл из Загрузок ===
input_file = r"C:\Users\efimo\Downloads\HR_IBM_first_100.csv"


# Загружаем CSV
df = pd.read_csv(input_file)
print(f"Файл {input_file} загружен успешно — {len(df)} строк")

# === Подключаемся к PostgreSQL ===
engine = create_engine(
    f"postgresql+psycopg2://{db_user}:{db_password}@{db_url}:{db_port}/{db_root_base}",
    pool_recycle=3600,  # переподключение каждые 60 минут
    echo=True,
)

# === Загружаем данные в PostgreSQL ===
df.to_sql(
    name="efimova",
    con=engine,
    schema="public",
    if_exists="replace",
    index=True,
)

# === Добавляем первичный ключ по индексу ===
with engine.begin() as conn:
    conn.execute(text('ALTER TABLE public.efimova ADD PRIMARY KEY (index)'))

# === Проверяем структуру таблицы ===
inspector = inspect(engine)
columns = inspector.get_columns("efimova", schema="public")
print("Структура таблицы:")
print({col["name"]: col["type"] for col in columns})

# === Пробуем просмотреть первые 5 строк из БД ===
with engine.begin() as conn:
    query = """
    SELECT *
    FROM public.efimova
    LIMIT 5
    """
    rows = conn.execute(text(query)).all()
    print("Первые 5 строк из таблицы efimova:")
    print(rows)