# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17hEkpTvP5vTgISfE-UpOnWXvWvYiLrcv
"""

import pandas as pd

df = pd.read_csv('/content/HR_IBM.csv')

# Оставляем только первые 100 строк
df_first_100 = df.head(100)

# Сохраняем результат в новый файл (опционально)
df_first_100.to_csv('HR_IBM_first_100.csv', index=False)